# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
eigenTransMatMult <- function(A, B) {
    .Call('_MyFunctions_eigenTransMatMult', PACKAGE = 'MyFunctions', A, B)
}

#' @export
eigenMatMult <- function(A, B) {
    .Call('_MyFunctions_eigenMatMult', PACKAGE = 'MyFunctions', A, B)
}

#' @export
eigenMapMatMult <- function(A, B) {
    .Call('_MyFunctions_eigenMapMatMult', PACKAGE = 'MyFunctions', A, B)
}

#' @export
ScalarMult <- function(X, y) {
    .Call('_MyFunctions_ScalarMult', PACKAGE = 'MyFunctions', X, y)
}

rcpp_hello_world <- function() {
    .Call('_MyFunctions_rcpp_hello_world', PACKAGE = 'MyFunctions')
}

#' Leading NA
#'
#' This function is an implementation of Gibbs sampler written by Dirk Eddelbuettel
#'
#' @param n Number of iterations
#' @param thn vector
#' @export
NULL

RcppGibbs <- function(n, thn) {
    .Call('_MyFunctions_RcppGibbs', PACKAGE = 'MyFunctions', n, thn)
}

